### ISSUE TITLE
"Unexpected end of file" error

### ISSUE THREAD

**Issue by ThomasLuypaertGitHub** [scikit-maad/scikit-maad#27]
When trying to open files for pre-processing, I get the following error:

![image](https://user-images.githubusercontent.com/52928299/77645554-2e73ae00-6f63-11ea-9179-572c8d7eda73.png)

I wasn't sure what was the cause of this. I've tried changing the filenames to match yours in the example, however that didn't seem to work. Any suggestions are most welcome.

**Comment by shaupert** [comment]
Hello Thomas, I don't know this error. You should have a look directly to scipy -> wavfile.py to see the cause of this error. I hope this helps.
Sylvain
