### ISSUE TITLE
rois mask example

### ISSUE THREAD

**Issue by YizharLavner** [scikit-maad/scikit-maad#41]
In maad.rois.cteate_mask in the example the smooth should be sound.smooth and not rois.smooth.
(in the example it appears as: Sxx_dB_blurred = maad.rois.smooth(Sxx_dB)   )
(https://scikit-maad.github.io/generated/maad.rois.create_mask.html#maad.rois.create_mask)
In addition the second plot in the example yields an empty plot: maad.util.plot2d(im_bin, ax=ax2, extent=ext, title='mask')

Thanks.

**Comment by juansulloa** [comment]
Hi Yizhar,

Thanks for spotting this bug on the docstring and for reporting the issue. 
We fixed it in the development version and will be available for the next minor release v1.3.1

Regards,
