### ISSUE TITLE
Find rois in a .wav file

### ISSUE THREAD

**Issue by tinchobulen** [scikit-maad/scikit-maad#42]
Hello,

I'm starting to use scikit-maad package for the analysis of my recordings. 
started with the finding of ROIs with my own .wav file. However, I found a problem with the sound.smooth() function.
could you please help me with this issue?
I'm a beginner with Python, probably there is an easy-to-catch mistake here!

please find attached my IPython script.

[rois_detection.txt](https://github.com/scikit-maad/scikit-maad/files/8412508/rois_detection.txt)

sincerely,

Martin.

**Comment by juansulloa** [comment]
Hi Martin,

I'm not able to replicate the error you had. The script is running fine in my computer using [this audio](https://github.com/scikit-maad/scikit-maad/blob/production/data/spinetail.wav).
I would first try the code with this audio sample. 
Run the code line by line and identify where is the error. It seems that you might be having the error with the plot function, so turn off the plot with `display=False` in the function `sound.smooth`

```
import numpy as np
import pandas as pd
from maad import sound, rois, features
from maad.util import (power2dB, plot2d, format_features, 
                       read_audacity_annot, overlay_rois, overlay_centroid)

s, fs = sound.load('./data/spinetail.wav')

dB_max = 96
Sxx_power, tn, fn, ext = sound.spectrogram(s, fs, nperseg=1024, noverlap=1024//2)
Sxx_db = power2dB(Sxx_power) + dB_max
plot2d(Sxx_db, **{'vmin':0, 'vmax':dB_max, 'extent':ext})

Sxx_power_noNoise= sound.median_equalizer(Sxx_power, display=True, **{'extent':ext})
Sxx_db_noNoise = power2dB(Sxx_power_noNoise)

Sxx_db_noNoise_smooth = sound.smooth(Sxx_db_noNoise, std=0.5, display=True, savefig=None, 
                                     **{'vmin':0, 'vmax':dB_max, 'extent':ext})
```

**Comment by tinchobulen** [comment]
Thank you Juan.

I see there is a problem with this plot function, maybe in my python environment.
not to worry, I will not give up!
I have managed to plot a spectrogram of my recording but, without the rois detection (see attached figure)

do you know any book about Python or an online course I can take?

![Figure_3](https://user-images.githubusercontent.com/43459951/165525932-e07342b3-6035-4672-b6a8-2c9d766856ec.png)

sincerely,

Martin.

**Comment by juansulloa** [comment]
Hi Martin,

The plot displays fine on my computer.
Try installing matplotlib version 3.1.1: `conda install matplotlib==3.1.1` or `pip install matplotlib==3.1.1`

```
from maad import sound, util, rois
s, fs = sound.load_url('spinetail')
rois.find_rois_cwt(s, fs, flims=(4500,8000), tlen=2, th=0, display=True)

```
![Figure_1](https://user-images.githubusercontent.com/17291469/199851499-54a0ac7d-71df-4789-a90f-30cd59767d77.png)

All the best,
