### ISSUE TITLE
Spectrogram to gray-scale image in python

### ISSUE THREAD

**Issue by dariodematties** [scikit-maad/scikit-maad#49]
Hi, I wanted to know the correct way of saving a spectrogram as a gray scale mono-channel image using your package

I have done something similar using librosa

```
def graph_mel_spectrogram_as_mono_channel(y, sr, n_mels, file_path):
    S = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=n_mels)
    data = librosa.power_to_db(S, ref=np.max)
    im = Image.fromarray(data.astype(np.uint8))
    im = im.resize((1024, 1024))
    im.save(file_path)


```
but when I use `fromarray` after `sound.spectrogram`  the image is all black

I can get a figure and save it using this

```
def from_spectrogram_to_figure(spectrogram, extent):
    fig, ax = plt.subplots(1,1, figsize=(10,6))
    fig.patch.set_visible(False)
    plt.axis('off')
    plt.autoscale(tight=True)
    util.plot_spectrogram(spectrogram, extent=extent, colorbar=False, ax=ax)
    return fig

```

but I don't want to use plotting functions in this way, I would like to use it properly

Any help?

Thanks!
Dario

**Comment by dariodematties** [comment]
> Hi Dario, Sorry for the delay, I do not have notifications. Have you already tried to use the argument `savefig` in the function spectrogram. You should be able to directly saved the spectrogram when calculating it by passing the full path of the file that you want to save ?
> 
> Sylvain

Thanks Sylvain! Could you write an example code of that? The idea is to save the spectrogram as a png grayscale monochannel image without any axes, just the pixels of the spectrogram. Is it possible to do that?

I have done it but using other things (I can share if needed). I would like to use a more standardized  way of the library and clean my code.

Thanks!

**Comment by shaupert** [comment]
Hi Dario, 

Please have a look to the colab to have an example of how to do it : https://colab.research.google.com/drive/15-rjuHSMsyj98v13X6LTJb6TvNtDArus?usp=sharing

Sylvain

**Comment by dariodematties** [comment]
Thanks so much Sylvain! I tested the code in my env and it is working!
Thanks,
Dario

**Comment by dariodematties** [comment]
Just a minor thing, instead of using ` spectro_image = spectro_image.rotate(180)`

You have to use ` spectro_image = spectro_image.transpose(Image.FLIP_TOP_BOTTOM)`

Thanks!
