### ISSUE TITLE
Mel scale spectrogram

### ISSUE THREAD

**Issue by dariodematties** [scikit-maad/scikit-maad#51]
Hi,
Can I easily compute Mel scale spectrograms using scikit-maad?
Thanks!

**Comment by juansulloa** [comment]
Hi,

Although we would like to have this feature, we have not yet developed it in scikit-maad.
You can compute Mel scale spectrograms on Python with [librosa](https://librosa.org/doc/latest/index.html).

All the best,

**Comment by dariodematties** [comment]
Thanks juansulloa!

I knew I can use librosa. My main aim was to use just one package for all my audio needs.

I will use both packages, scikit maad and librosa

Thanks for this amazing package!

Best

Dario
