### ISSUE TITLE
`multichannel` is a deprecated for `transform.rescale function`

### ISSUE THREAD

**Issue by saguileran** [scikit-maad/scikit-maad#53]
FutureWarning with transform.function:
.\plot_nmf_and_false_color_spectrogram.py:42: FutureWarning: `multichannel` is a deprecated argument name for `rescale`. It will be removed in version 1.0. Please use `channel_axis` instead.

The problem is also in the function transform.pyramid_gaussian and in the file shape.py, line  340, 343, 359

Solution: Change multichannel=False by channel_axis=None
https://github.com/scikit-image/scikit-image/issues/4294

**Comment by shaupert** [comment]
We removed the argument as we do not need it.
