### ISSUE TITLE
`frame.append` method is deprecated, change by `pandas.concat` 

### ISSUE THREAD

**Issue by saguileran** [scikit-maad/scikit-maad#54]
FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

This warning appears in the files:
- plot_xenocanto_wookpecker_activities.py lines 123 and 149
- xeno-canto.py lines 97, 224 and 229

**Comment by shaupert** [comment]
We replaced append method by concat method everywhere
