### ISSUE TITLE
TFSD: threshold in documentation, and other approach

### ISSUE THREAD

**Issue by modantailleur** [scikit-maad/scikit-maad#58]
With the new patch of the TFSD, the threshold of 0.3 for birds in the documentation https://scikit-maad.github.io/generated/maad.features.tfsd.html#maad.features.tfsd is not true anymore. If a log is used on the spectrogram, results of TFSD are between 0.4 and 0.5 for any audio file containing or not birds. The correlations with presence of birds when using a log spectrogram remains practically identical, which makes it still relevant, it just changes the scale.

The threshold of 0.3 seems to work with an implementation with a spectrogram in amplitude, and a tfsd without a log on the spectrogram.  This also correlates with the presence of birds. With the current version of the TFSD, you would need to write something like this to get it, in order to invert the log:

`s, fs = maad.sound.load('../data/cold_forest_daylight.wav')`
`Sxx_power,tn,fn,_ = maad.sound.spectrogram(s,fs,mode='amplitude')`
`Sxx_power = 10**Sxx_power`
`maad.features.tfsd(Sxx_power,fn, tn)  `
 
A solution for people wanting to use the amplitude non log version with the 0.3 threshold could be to put an optional argument to the TFSD function, which would be True by default ( `log=True` ). I think that it is safer now to remove the threshold indication of 0.3 in the documentation, and just indicate that it correlates with the presence of birds.

**Comment by shaupert** [comment]
Thanks @modantailleur  to point the discrepancy.
We fix the issue in the doc and add as you suggest an argument `log=True` in the function.
