### ISSUE TITLE
Continuous integration?

### ISSUE THREAD

**Issue by carueda** [scikit-maad/scikit-maad#59]
Howdy! I recently learned about MAAD and got interested. I don't have any immediate need for it but was just looking at it from a potential contributor point of view and wondering about aspects not mentioned in the wiki AFAICT like unit testing (unittest, pytest, ...), continuous integration (that is, Github actions to run tests upon pushes or pull requests), etc.  Again, this is just a heads-up,   and apologies if I'm just not looking into the right docs. Thanks.

**Comment by carueda** [comment]
Sorry, how come I missed to find https://github.com/scikit-maad/scikit-maad/wiki/Test-modules !

So, I'm changing the title of this ticket.

**Comment by juansulloa** [comment]
I Carlos,

Currently the documentation for testing and to make contribution is on the wiki of the package. However, we will add a CONTRIBUTING.md file to facilitate contributions from the community.

This will be updated soon.
