### ISSUE TITLE
Port the system to more recent library versions

### ISSUE THREAD

**Issue by Bengt** [scikit-maad/scikit-maad#64]
This system currently requires dated versions of numpy, scikit and matplotlib. This hinders support for macOS on Apple Silicone. Therefore, this system should be ported to the latest versions of the direct dependencies.

**Comment by shaupert** [comment]
Thanks @Bengt.  For the next release 1.4.0, scikit-maad will be compliant with the most recent version of numpy, scikit-image, pandas and matplolib. We also added the supported systems in the readme as you suggested.

**Comment by Bengt** [comment]
Awesome! Thanks for the feedback.
