### ISSUE TITLE
Test the doc strings using doctest

### ISSUE THREAD

**Issue by Bengt** [scikit-maad/scikit-maad#68]
There are quite a lot of usage examples in the documentation strings. Searching ">>> " yields 422 results for me. Currently, these go untested and can therefore easily break due to code changes like refactoings. To avoid that, please use [doctest](https://docs.python.org/3/library/doctest.html) to test these documentation strings in CI and also locally.

**Comment by shaupert** [comment]
Great suggestions ! We're gonna use it and try to integrate doctest with pytest. It seems that the command pytest --doctest-modules -sv is doing that but we need to check.
