### ISSUE TITLE
BUG:  util.date_parser() not working for audiomoth naming format

### ISSUE THREAD

**Issue by diegryllid** [scikit-maad/scikit-maad#83]
**Describe the bug**
The util.date_parser() function does not recognize Audiomoth file naming date format (ex. 20220607_023200.WAV).

**To Reproduce**

1. Run command:
from maad import sound, util, spl

df = util.date_parser("D:/maads/", dateformat="POSIX", verbose=True)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Diego\AppData\Local\Programs\Python\PYTHON~2\Lib\site-packages\maad\util\parser.py", line 399, in date_parser
    dd = datetime.utcfromtimestamp(posix_time).strftime('%Y-%m-%d %H:%M:%S')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument

**Expected behavior**
I expected it to parse the dates from the file names.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Python version: 3.11.0
 - maad version: 1.4.0

**Comment by shaupert** [comment]
Hi, thanks for the report and the commit. I will have a look to the bug as soon as possible.
Best
Sylvain

**Comment by shaupert** [comment]
Hi,
We fixed the issue in the last release 1.4.2
