### ISSUE TITLE
BUG: when using rois.template_matching(... display = True) shows error

### ISSUE THREAD

**Issue by wl415** [scikit-maad/scikit-maad#85]
When using rois.template_matiching( ... display = True) shows:

Traceback (most recent call last):
  File "c:\Users\Acer\Documents\ecoacoustic project\loading and analyzing sounds.py", line 18, in <module>
    corr, detected = rois.template_matching(spec1, spec, tn1, ext, 0.1, display = True)
  File "C:\Users\Acer\anaconda3\lib\site-packages\maad\rois\template_matching_func.py", line 172, in template_matching
    xy = (rois.min_t[idx], rois.min_f[idx])
  File "C:\Users\Acer\anaconda3\lib\site-packages\pandas\core\generic.py", line 6202, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'min_f'

This is due to the source code:

    rois = pd.DataFrame(
        {
            "peak_time": peaks_time,
            "xcorrcoef": xcorrcoef[peaks],
            "min_t": peaks_time - template_len / 2,
            "max_t": peaks_time + template_len / 2,
        }
    )

where frequency related parameters are not defined.

OS: Windpws 10
Python: 3.9.7
Maad: 1.4.0

**Comment by juansulloa** [comment]
Hi,

Thanks for reporting this bug.
I modified the function to be able to visualize the results on [this commit](https://github.com/scikit-maad/scikit-maad/commit/c8fd012ced6ef52ebe5eb8f3b0ef9690817fc60f).

Note: To better visualize the output of template matching, check [this example](https://scikit-maad.github.io/_auto_examples/1_basic/plot_template_matching_example.html#sphx-glr-auto-examples-1-basic-plot-template-matching-example-py).

All the best,
