### ISSUE TITLE
How does scikitt maad estimate the attenuation?

### ISSUE THREAD

**Issue by ss3443** [scikit-maad/scikit-maad#89]
For the attenuation you combine the attenuation due to different effects: the geometrical spreading, the atmospheric attenuation and the habitat attenuation coefficient. Do you have a reference for the equations you used to calculate this? 
Especially that for habitat attenuation, as surely this would vary vastly depending on the location that you are in and the function doesn't seem to have any parameters relating to this. 

I am asking as I am hoping to use scikitmaad for the analysis of my project. A speedy reply would be much appreciated.  

Thank you in advance, 
Srishty

**Comment by shaupert** [comment]
Please, have a look to the paper Haupert, S., Sèbe, F., & Sueur, J. (2023). Physics‐based model to predict the acoustic detection distance of terrestrial autonomous recording units over the diel cycle and across seasons: Insights from an Alpine and a Neotropical forest. Methods in Ecology and Evolution https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.14020. You'll get all the information that you need to understand the functions.
