### ISSUE TITLE
BUG: rois.find_rois_cwt does not execute 

### ISSUE THREAD

**Issue by jokot025** [scikit-maad/scikit-maad#93]
**Describe the bug**
When running code for finding ROIs on my own data I get a TypeError saying that firwin got an unexpected keyword argument.   

**To Reproduce**
1. run  ```rois.find_rois_cwt```
2. TypeError: firwin() got an unexpected keyword argument 'nyq'

```python
from maad import sound, rois

s, fs = sound.load('PATH_TO_FILE')

rois.find_rois_cwt(s, fs, flims=(35000,45000), tlen=0.02, th=0, display=True)
```

```
 Traceback (most recent call last):

  File ~/spyder/lib/python3.12/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~/Faks tingz/Python/untitled2.py:5
    rois.find_rois_cwt(s, fs, flims=(35000,45000), tlen=0.02, th=0, display=True)

  File ~/spyder/lib/python3.12/site-packages/maad/rois/rois_1d.py:153 in find_rois_cwt
    s_filt = sinc(s, flims, fs, atten=80, transition_bw=0.8)

  File ~/spyder/lib/python3.12/site-packages/maad/sound/filter.py:273 in sinc
    taps = firwin(

TypeError: firwin() got an unexpected keyword argument 'nyq'
```

**Expected behavior**
Producing a spectrogram with marked ROIs.

**Desktop:**
 - OS: Linux Mint 22.
 - Spyder 3.12
 - maad version 1.4.2

**Comment by shaupert** [comment]
Hi, thanks to point out the bug. I've just fixed it. It should work now for scipy >= 1.12.0. Please wait for the next update of pypi package.

**Comment by juansulloa** [comment]
We have recently made a new release and updated the package in PyPi v1.4.3 with this bug fixed.
Please update scikit-maad and test again.
