### ISSUE TITLE
BUG: TypeError: firwin() got an unexpected keyword argument 'nyq'

### ISSUE THREAD

**Issue by charlie-garcia** [scikit-maad/scikit-maad#95]
When trying to run the ROI example on the Quick Start page:
rois.find_rois_cwt(s, fs, flims=(4500,8000), tlen=2, th=0, display=True)

this error shows up:
TypeError: firwin() got an unexpected keyword argument 'nyq'

I'm using 
scipy=1.14.0
numpy=1.26.4

By modifing the file maad/sound/filter.py in lines 273-281

```python
 taps = firwin(
         numtaps, 
         cutoff, 
         window=('kaiser', beta), 
         scale=False, 
         pass_zero=not(bandpass),
         fs=fs,
) ```

solved the issue: I don't know if with previous versions of scipy you get this error.

**Comment by shaupert** [comment]
Hi, thanks to point out the bug. I've just fixed it. It should work now for scipy >= 1.12.0. Please wait for the next update of pypi package.

**Comment by juansulloa** [comment]
We have recently made a new release and updated the package in PyPi v1.4.3 with this bug fixed.
Please update scikit-maad and test again.
